### ISSUE TITLE
untar unzip to the folder under MacOS

### ISSUE THREAD

**Issue by drom** [drom/simple-nwjs-app#1]
Having issue with untarring / unzipping into the folder under MacOS.

`tar -xvsf cache/pak.tar.gz -C cache`
https://github.com/drom/simple-nwjs-app/blob/master/build.sh#L20

Works under Linux:
https://travis-ci.org/drom/simple-nwjs-app/jobs/155606858#L153

Fails under MacOS:
https://travis-ci.org/drom/simple-nwjs-app/jobs/155606859#L55

@polpo any advise?

**Comment by polpo** [comment]
I think this is because macOS uses BSD tar instead of GNU tar. The `-s` option is for modifying file names in BSD tar (similar to GNU tar `--transform` option) instead of preserving file order like in GNU tar. Is the `-s` option necessary?

**Comment by drom** [comment]
No, I don't think `-s` is required.

**Comment by drom** [comment]
Thank you @polpo . It helps. Now script works under MacOS.
Fixed in 48886178c6064e6ae0386c8bd16c2fa5862cfef9
