### ISSUE TITLE
urlget brakes the build process when file already exists

### ISSUE THREAD

**Issue by drom** [drom/simple-nwjs-app#11]
Looks like the way we are calling `wget` from inside `urlget` subroutine brakes the build flow when file already downloaded.
@polpo any ideas why?

**Comment by polpo** [comment]
I thought the `-nc` option to wget would prevent that. But in any case, moving the `if ! [ -f "$2" ]; then` file existence conditional for curl up to the top of the `urlget` function should fix it.

**Comment by drom** [comment]
@polpo Yes, `-nc` checks file existence, but it probably returns some weird return code or something, so script stops right there ;)
