### ISSUE TITLE
Osx-x64 build of simpleapp - screenshot attached

### ISSUE THREAD

**Issue by ajgrande924** [drom/simple-nwjs-app#9]
![image](https://cloud.githubusercontent.com/assets/12506734/21160597/4495db70-c13a-11e6-8707-36b55a39bbbe.png)

can be found in simple-nwjs-app/cache/simpleapp-v1.0.0-osx-x64/nwjs after running build.sh

**Comment by drom** [comment]
@polpo looks like we have issue with the OSX build. Could you try running it?

**Comment by drom** [comment]
## related:
https://github.com/wavedrom/wavedrom.github.io/issues/22
http://docs.nwjs.io/en/latest/For%20Users/Package%20and%20Distribute/#mac-os-x
http://docs.nwjs.io/en/latest/For%20Users/Advanced/Support%20for%20Mac%20App%20Store/
